### ISSUE TITLE
Remove links using names with dash characters inside the playbook folder

### ISSUE THREAD

**Issue by shellclear** [validatedpatterns/rhvp.cluster_utils#21]
The usage of dash is not supported to run playbook names in collections.

https://docs.ansible.com/ansible/latest/collections_guide/collections_using_playbooks.html

**Comment by shellclear** [comment]
PR opened

[https://github.com/validatedpatterns/rhvp.cluster_utils/pull/22](url)

**Comment by mbaldessari** [comment]
Thanks! Fixed by https://github.com/validatedpatterns/rhvp.cluster_utils/pull/22
